In [32]:
import pandas as pd
from textblob import TextBlob
import re
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from wordcloud import WordCloud
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
from nltk.stem.snowball import SnowballStemmer
from keras.preprocessing import sequence
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer
import re
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_score, recall_score
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()

In [33]:
file_path = r"C:\Users\DIKY\tweets-data\DATA BERSIH.csv"
df=pd.read_csv(file_path)
df

Unnamed: 0                                               text  \
0              0  ['pemerintah', 'hapus', 'kelas', 'dulunya', 'k...   
1              1  ['rancangan', 'asuransi', 'meringankan', 'perk...   
2              2  ['bikin', 'perpanjang', 'berlaku', 'menyertaka...   
3              3  ['konsep', 'gotong', 'royong', 'berkeadilan', ...   
4              4                    ['password', 'social', 'media']   
...          ...                                                ...   
1352        1352  ['layangan', 'vaksin', 'internasional', 'kebut...   
1353        1353                 ['pemeriksaan', 'kenal', 'risiko']   
1354        1354  ['vaksin', 'covid', 'bayar', 'ratusan', 'ribu'...   
1355        1355  ['keliru', 'konten', 'pemasangan', 'microchip'...   
1356        1356  ['cacar', 'monyet', 'mengkhawatirkan', 'indone...   

      polarity_score polarity  \
0                -24  negatif   
1                 -6  negatif   
2                -11  negatif   
3                  0  positif   
4                  0  positif   
...              ...      ...   
1352              -4  negatif   
1353               0  positif   
1354              -1  negatif   
1355              -2  negatif   
1356               4  positif   

                                        stemming_ulasan  
0     perintah hapus kelas dulunya kelas sama standa...  
1     rancang asuransi ringan kembang berat masyarak...  
2       bikin panjang laku serta bpjs sehat aktif polri  
3     konsep gotong royong adil jadi butuh politis b...  
4                                 password social media  
...                                                 ...  
1352  layang vaksin internasional butuh ela pandemi ...  
1353                               periksa kenal risiko  
1354  vaksin covid bayar ratus ribu kemenkes mumpung...  
1355  keliru konten pasang microchip vaksinasi indon...  
1356  cacar monyet khawatir indonesia kaltara dampak...  

[1357 rows x 5 columns]

In [34]:
df.isna().sum()

Unnamed: 0          0
text                0
polarity_score      0
polarity            0
stemming_ulasan    33
dtype: int64

In [35]:
df.dropna(subset=['stemming_ulasan'], inplace=True)


In [36]:
X_train, X_test, y_train, y_test = train_test_split(df['stemming_ulasan'], df['polarity'],
                                                    test_size = 0.30,
                                                    random_state = 42)

In [37]:
X = df['stemming_ulasan']
y = df['polarity']

In [38]:
#PEMBOBOTAN
tfidf_vectorizer = TfidfVectorizer()
tfidf_train = tfidf_vectorizer.fit_transform(X_train)
tfidf_test = tfidf_vectorizer.transform(X_test)

In [39]:
# PROSES TF IDF
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer()
text_tf = tf.fit_transform(df['stemming_ulasan'].astype('U'))
print(text_tf)

  (0, 3183)	0.22379204705752678
  (0, 1998)	0.16790980425654
  (0, 1247)	0.14101701982684367
  (0, 913)	0.20309829024985598
  (0, 344)	0.1702994617106547
  (0, 408)	0.08879504241910986
  (0, 1032)	0.17289716725635043
  (0, 2968)	0.44758409411505357
  (0, 2692)	0.1702994617106547
  (0, 751)	0.22379204705752678
  (0, 1418)	0.6935288681100086
  (0, 1061)	0.13588646815771158
  (0, 2297)	0.12225004639015728
  (1, 3050)	0.3362525055408212
  (1, 3091)	0.27463714100183817
  (1, 1665)	0.14679271745261258
  (1, 3313)	0.5079864609845872
  (1, 2896)	0.21841179574770303
  (1, 1834)	0.17289673920142698
  (1, 1432)	0.29607144631159954
  (1, 2608)	0.3226098765046901
  (1, 201)	0.3033816708335089
  (1, 2524)	0.3120278313100076
  (1, 344)	0.2705108361261966
  (2, 2363)	0.4256348598150162
  :	:
  (1319, 1834)	0.20379669498956102
  (1320, 2293)	0.5999366504277769
  (1320, 2613)	0.5999366504277769
  (1320, 1443)	0.5292938984600132
  (1321, 1970)	0.510850217046805
  (1321, 559)	0.2521894434908619
  (1321, 3

In [40]:
tfidf = TfidfVectorizer()
text_tf = tfidf.fit_transform(df['stemming_ulasan'].astype('U'))

# Konversi hasil TF-IDF ke dalam DataFrame
tfidf_df = pd.DataFrame(text_tf.toarray(), columns=tfidf.get_feature_names_out(), index=df.index)

# Tampilkan DataFrame sebagai tabel
tfidf_df

aamiin  aangeboden  aanricht  abad  abang  abdi  abdomen  abdul  about  \
0        0.0         0.0       0.0   0.0    0.0   0.0      0.0    0.0    0.0   
1        0.0         0.0       0.0   0.0    0.0   0.0      0.0    0.0    0.0   
2        0.0         0.0       0.0   0.0    0.0   0.0      0.0    0.0    0.0   
3        0.0         0.0       0.0   0.0    0.0   0.0      0.0    0.0    0.0   
4        0.0         0.0       0.0   0.0    0.0   0.0      0.0    0.0    0.0   
...      ...         ...       ...   ...    ...   ...      ...    ...    ...   
1352     0.0         0.0       0.0   0.0    0.0   0.0      0.0    0.0    0.0   
1353     0.0         0.0       0.0   0.0    0.0   0.0      0.0    0.0    0.0   
1354     0.0         0.0       0.0   0.0    0.0   0.0      0.0    0.0    0.0   
1355     0.0         0.0       0.0   0.0    0.0   0.0      0.0    0.0    0.0   
1356     0.0         0.0       0.0   0.0    0.0   0.0      0.0    0.0    0.0   

      absah  ...  zijn  zionis   zm  zoals  zolang  zolim  zoon  zorg  zorgen  \
0       0.0  ...   0.0     0.0  0.0    0.0     0.0    0.0   0.0   0.0     0.0   
1       0.0  ...   0.0     0.0  0.0    0.0     0.0    0.0   0.0   0.0     0.0   
2       0.0  ...   0.0     0.0  0.0    0.0     0.0    0.0   0.0   0.0     0.0   
3       0.0  ...   0.0     0.0  0.0    0.0     0.0    0.0   0.0   0.0     0.0   
4       0.0  ...   0.0     0.0  0.0    0.0     0.0    0.0   0.0   0.0     0.0   
...     ...  ...   ...     ...  ...    ...     ...    ...   ...   ...     ...   
1352    0.0  ...   0.0     0.0  0.0    0.0     0.0    0.0   0.0   0.0     0.0   
1353    0.0  ...   0.0     0.0  0.0    0.0     0.0    0.0   0.0   0.0     0.0   
1354    0.0  ...   0.0     0.0  0.0    0.0     0.0    0.0   0.0   0.0     0.0   
1355    0.0  ...   0.0     0.0  0.0    0.0     0.0    0.0   0.0   0.0     0.0   
1356    0.0  ...   0.0     0.0  0.0    0.0     0.0    0.0   0.0   0.0     0.0   

      zoveel  
0        0.0  
1        0.0  
2        0.0  
3        0.0  
4        0.0  
...      ...  
1352     0.0  
1353     0.0  
1354     0.0  
1355     0.0  
1356     0.0  

[1324 rows x 3510 columns]

In [41]:
random_num = []
matrix = []
report = []
acc_num = []
re_num = []
pre_num = []
test_num = []

for test in [0.1, 0.2, 0.3, 0.4]:
    random = 42
    print("test size:", test)
    print("random state:", random)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test, random_state=random)
    vectorizer = TfidfVectorizer(use_idf=True, smooth_idf=False)
    X_train_vect = vectorizer.fit_transform(X_train)
    X_test_vect = vectorizer.transform(X_test)
    SVM = SVC(kernel='linear')
    SVM.fit(X_train_vect, y_train)
    train_score = SVM.score(X_train_vect, y_train)  # Store training score
    print(train_score)
    predict = SVM.predict(X_test_vect)
    accuracy = accuracy_score(y_test, predict)
    confusion = confusion_matrix(y_test, predict)
    print('confusion matrix:\n', confusion)
    classification = classification_report(y_test, predict)  # Removed print() here
    print(classification)  # Print the classification report directly
    print("Accuracy Score:", round(accuracy, 2))

    recall = recall_score(y_test, predict, average='weighted')  # Adjusted averaging strategy here
    print("Recall Score:", recall)
    precision = precision_score(y_test, predict, average='weighted')  # Adjusted averaging strategy here
    print("Precision Score:", precision)
    print("\n")

    random_num.append(random)
    matrix.append(confusion)
    report.append(classification)  # Storing the classification report directly
    acc_num.append(accuracy)
    re_num.append(recall)
    pre_num.append(precision)
    test_num.append(test)
    print("=================================================================")

test size: 0.1
random state: 42
0.9538203190596137
confusion matrix:
 [[58 16]
 [17 42]]
              precision    recall  f1-score   support

     negatif       0.77      0.78      0.78        74
     positif       0.72      0.71      0.72        59

    accuracy                           0.75       133
   macro avg       0.75      0.75      0.75       133
weighted avg       0.75      0.75      0.75       133

Accuracy Score: 0.75
Recall Score: 0.7518796992481203
Precision Score: 0.7515098090052718


test size: 0.2
random state: 42
0.9575070821529745
confusion matrix:
 [[115  36]
 [ 30  84]]
              precision    recall  f1-score   support

     negatif       0.79      0.76      0.78       151
     positif       0.70      0.74      0.72       114

    accuracy                           0.75       265
   macro avg       0.75      0.75      0.75       265
weighted avg       0.75      0.75      0.75       265

Accuracy Score: 0.75
Recall Score: 0.7509433962264151
Precision Score: 0

In [42]:
data = {'test_size':test_num,
        'random_state':random_num,
        'confusion_matrix': matrix,
        'accuracy': acc_num,
        'recall': re_num,
        'precision': pre_num}

optimal = pd.DataFrame(data)
optimal
# optimal = optimal.sort_values(by=['accuracy','recall','precision'], ascending=True)

test_size  random_state        confusion_matrix  accuracy    recall  \
0        0.1            42    [[58, 16], [17, 42]]  0.751880  0.751880   
1        0.2            42   [[115, 36], [30, 84]]  0.750943  0.750943   
2        0.3            42  [[164, 58], [54, 122]]  0.718593  0.718593   
3        0.4            42  [[213, 77], [81, 159]]  0.701887  0.701887   

   precision  
0   0.751510  
1   0.753051  
2   0.719342  
3   0.701504

In [43]:
optimal['accuracy'] = optimal['accuracy'].apply(lambda floats:format(float(floats), ".2f"))
optimal['recall'] = optimal['recall'].apply(lambda floats:format(float(floats), ".2f"))
optimal['precision'] = optimal['precision'].apply(lambda floats:format(float(floats), ".2f"))
optimal['test_size'] = optimal['test_size'].apply(lambda floats:format(float(floats), ".1f"))
optimal

test_size  random_state        confusion_matrix accuracy recall precision
0       0.1            42    [[58, 16], [17, 42]]     0.75   0.75      0.75
1       0.2            42   [[115, 36], [30, 84]]     0.75   0.75      0.75
2       0.3            42  [[164, 58], [54, 122]]     0.72   0.72      0.72
3       0.4            42  [[213, 77], [81, 159]]     0.70   0.70      0.70

In [44]:
#@ NAIVE BAYES

In [45]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, recall_score, precision_score

random_num = []
matrix = []
report = []
acc_num = []
re_num = []
pre_num = []
test_num = []

for test in [0.1, 0.2, 0.3, 0.4]:
    random = 42
    print("test size:", test)
    print("random state:", random)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test, random_state=random)
    vectorizer = TfidfVectorizer(use_idf=True, smooth_idf=False)
    X_train_vect = vectorizer.fit_transform(X_train)
    X_test_vect = vectorizer.transform(X_test)
    
    # Menggunakan algoritma Naive Bayes
    naive_bayes_model = MultinomialNB()  # Gunakan MultinomialNB
    naive_bayes_model.fit(X_train_vect, y_train)
    predict = naive_bayes_model.predict(X_test_vect)
    
    accuracy = accuracy_score(y_test, predict)
    confusion = confusion_matrix(y_test, predict)
    print('confusion matrix:\n', confusion)
    classification = classification_report(y_test, predict)
    print(classification)
    print("Accuracy Score:", round(accuracy, 2))

    recall = recall_score(y_test, predict, average='weighted')
    print("Recall Score:", recall)
    precision = precision_score(y_test, predict, average='weighted')
    print("Precision Score:", precision)
    print("\n")

    random_num.append(random)
    matrix.append(confusion)
    report.append(classification)
    acc_num.append(accuracy)
    re_num.append(recall)
    pre_num.append(precision)
    test_num.append(test)
    print("=================================================================")


test size: 0.1
random state: 42
confusion matrix:
 [[61 13]
 [22 37]]
              precision    recall  f1-score   support

     negatif       0.73      0.82      0.78        74
     positif       0.74      0.63      0.68        59

    accuracy                           0.74       133
   macro avg       0.74      0.73      0.73       133
weighted avg       0.74      0.74      0.73       133

Accuracy Score: 0.74
Recall Score: 0.7368421052631579
Precision Score: 0.7371845275840203


test size: 0.2
random state: 42
confusion matrix:
 [[117  34]
 [ 40  74]]
              precision    recall  f1-score   support

     negatif       0.75      0.77      0.76       151
     positif       0.69      0.65      0.67       114

    accuracy                           0.72       265
   macro avg       0.72      0.71      0.71       265
weighted avg       0.72      0.72      0.72       265

Accuracy Score: 0.72
Recall Score: 0.720754716981132
Precision Score: 0.7193953718169558


test size: 0.3
rand

In [46]:
data = {'test_size':test_num,
        'random_state':random_num,
        'confusion_matrix': matrix,
        'accuracy': acc_num,
        'recall': re_num,
        'precision': pre_num}

optimal = pd.DataFrame(data)
optimal
# optimal = optimal.sort_values(by=['accuracy','recall','precision'], ascending=True)

test_size  random_state        confusion_matrix  accuracy    recall  \
0        0.1            42    [[61, 13], [22, 37]]  0.736842  0.736842   
1        0.2            42   [[117, 34], [40, 74]]  0.720755  0.720755   
2        0.3            42  [[171, 51], [64, 112]]  0.711055  0.711055   
3        0.4            42  [[220, 70], [77, 163]]  0.722642  0.722642   

   precision  
0   0.737185  
1   0.719395  
2   0.709731  
3   0.722098

In [47]:
#@ DECISION TREE

In [48]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, recall_score, precision_score

random_num_rf = []
matrix_rf = []
report_rf = []
acc_num_rf = []
re_num_rf = []
pre_num_rf = []
test_num_rf = []

random_num_dt = []
matrix_dt = []
report_dt = []
acc_num_dt = []
re_num_dt = []
pre_num_dt = []
test_num_dt = []

for test in [0.1, 0.2, 0.3, 0.4]:
    random = 42
    print("test size:", test)
    print("random state:", random)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test, random_state=random)
    vectorizer = TfidfVectorizer(use_idf=True, smooth_idf=False)
    X_train_vect = vectorizer.fit_transform(X_train)
    X_test_vect = vectorizer.transform(X_test)
    
#     # Random Forest
#     rf_classifier = RandomForestClassifier()
#     rf_classifier.fit(X_train_vect, y_train)
#     train_score_rf = rf_classifier.score(X_train_vect, y_train)
#     print("Random Forest Training Score:", train_score_rf)
#     predict_rf = rf_classifier.predict(X_test_vect)
#     accuracy_rf = accuracy_score(y_test, predict_rf)
#     confusion_rf = confusion_matrix(y_test, predict_rf)
#     print('Random Forest Confusion Matrix:\n', confusion_rf)
#     classification_rf = classification_report(y_test, predict_rf)
#     print("Random Forest Classification Report:\n", classification_rf)
#     print("Random Forest Accuracy Score:", round(accuracy_rf, 2))
#     recall_rf = recall_score(y_test, predict_rf, average='weighted')
#     print("Random Forest Recall Score:", recall_rf)
#     precision_rf = precision_score(y_test, predict_rf, average='weighted')
#     print("Random Forest Precision Score:", precision_rf)
#     print("\n")
#     random_num_rf.append(random)
#     matrix_rf.append(confusion_rf)
#     report_rf.append(classification_rf)
#     acc_num_rf.append(accuracy_rf)
#     re_num_rf.append(recall_rf)
#     pre_num_rf.append(precision_rf)
#     test_num_rf.append(test)
#     print("=================================================================")
    
    # Decision Tree
    dt_classifier = DecisionTreeClassifier()
    dt_classifier.fit(X_train_vect, y_train)
    train_score_dt = dt_classifier.score(X_train_vect, y_train)
    print("Decision Tree Training Score:", train_score_dt)
    predict_dt = dt_classifier.predict(X_test_vect)
    accuracy_dt = accuracy_score(y_test, predict_dt)
    confusion_dt = confusion_matrix(y_test, predict_dt)
    print('Decision Tree Confusion Matrix:\n', confusion_dt)
    classification_dt = classification_report(y_test, predict_dt)
    print("Decision Tree Classification Report:\n", classification_dt)
    print("Decision Tree Accuracy Score:", round(accuracy_dt, 2))
    recall_dt = recall_score(y_test, predict_dt, average='weighted')
    print("Decision Tree Recall Score:", recall_dt)
    precision_dt = precision_score(y_test, predict_dt, average='weighted')
    print("Decision Tree Precision Score:", precision_dt)
    print("\n")
    random_num_dt.append(random)
    matrix_dt.append(confusion_dt)
    report_dt.append(classification_dt)
    acc_num_dt.append(accuracy_dt)
    re_num_dt.append(recall_dt)
    pre_num_dt.append(precision_dt)
    test_num_dt.append(test)
    print("=================================================================")


test size: 0.1
random state: 42
Decision Tree Training Score: 1.0
Decision Tree Confusion Matrix:
 [[49 25]
 [15 44]]
Decision Tree Classification Report:
               precision    recall  f1-score   support

     negatif       0.77      0.66      0.71        74
     positif       0.64      0.75      0.69        59

    accuracy                           0.70       133
   macro avg       0.70      0.70      0.70       133
weighted avg       0.71      0.70      0.70       133

Decision Tree Accuracy Score: 0.7
Decision Tree Recall Score: 0.6992481203007519
Decision Tree Precision Score: 0.708867957938324


test size: 0.2
random state: 42
Decision Tree Training Score: 1.0
Decision Tree Confusion Matrix:
 [[96 55]
 [25 89]]
Decision Tree Classification Report:
               precision    recall  f1-score   support

     negatif       0.79      0.64      0.71       151
     positif       0.62      0.78      0.69       114

    accuracy                           0.70       265
   macro av

In [49]:
import pandas as pd

data_dt = {'test_size': test_num_dt,
           'random_state': random_num_dt,
           'confusion_matrix': matrix_dt,
           'accuracy': acc_num_dt,
           'recall': re_num_dt,
           'precision': pre_num_dt}

optimal_dt = pd.DataFrame(data_dt)

# Format confusion matrix, accuracy, recall, dan precision
optimal_dt['confusion_matrix'] = optimal_dt['confusion_matrix'].apply(lambda x: str(x))
optimal_dt['accuracy'] = optimal_dt['accuracy'].apply(lambda x: round(x, 6))
optimal_dt['recall'] = optimal_dt['recall'].apply(lambda x: round(x, 6))
optimal_dt['precision'] = optimal_dt['precision'].apply(lambda x: round(x, 6))

optimal_dt


test_size  random_state         confusion_matrix  accuracy    recall  \
0        0.1            42      [[49 25]\n [15 44]]  0.699248  0.699248   
1        0.2            42      [[96 55]\n [25 89]]  0.698113  0.698113   
2        0.3            42  [[144  78]\n [ 44 132]]  0.693467  0.693467   
3        0.4            42  [[175 115]\n [ 75 165]]  0.641509  0.641509   

   precision  
0   0.708868  
1   0.717962  
2   0.705204  
3   0.649865

In [50]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, recall_score, precision_score

random_num = []
matrix = []
report = []
acc_num = []
re_num = []
pre_num = []
test_num = []

for test in [0.1, 0.2, 0.3, 0.4]:
    random = 42
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test, random_state=random)
    vectorizer = TfidfVectorizer(use_idf=True, smooth_idf=False)
    X_train_vect = vectorizer.fit_transform(X_train)
    X_test_vect = vectorizer.transform(X_test)
    SVM = SVC(kernel='linear')
    SVM.fit(X_train_vect, y_train)
    train_score = SVM.score(X_train_vect, y_train)
    predict = SVM.predict(X_test_vect)
    accuracy = accuracy_score(y_test, predict)
    confusion = confusion_matrix(y_test, predict)
    classification = classification_report(y_test, predict)
    recall = recall_score(y_test, predict, average='weighted')
    precision = precision_score(y_test, predict, average='weighted')

    random_num.append(random)
    matrix.append(confusion)
    report.append(classification)
    acc_num.append(accuracy)
    re_num.append(recall)
    pre_num.append(precision)
    test_num.append(test)

data = {'test_size': test_num,
        'random_state': random_num,
        'confusion_matrix': [str(m) for m in matrix],  # Convert confusion matrices to strings
        'accuracy': acc_num,
        'recall': re_num,
        'precision': pre_num}

optimal = pd.DataFrame(data)
print(optimal)


   test_size  random_state         confusion_matrix  accuracy    recall  \
0        0.1            42      [[58 16]\n [17 42]]  0.751880  0.751880   
1        0.2            42  [[115  36]\n [ 30  84]]  0.750943  0.750943   
2        0.3            42  [[164  58]\n [ 54 122]]  0.718593  0.718593   
3        0.4            42  [[213  77]\n [ 81 159]]  0.701887  0.701887   

   precision  
0   0.751510  
1   0.753051  
2   0.719342  
3   0.701504  


In [51]:
#@ RANDOM FOREST

In [52]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, recall_score, precision_score

random_num_rf = []
matrix_rf = []
report_rf = []
acc_num_rf = []
re_num_rf = []
pre_num_rf = []
test_num_rf = []

random_num_dt = []
matrix_dt = []
report_dt = []
acc_num_dt = []
re_num_dt = []
pre_num_dt = []
test_num_dt = []

for test in [0.1, 0.2, 0.3, 0.4]:
    random = 42
    print("test size:", test)
    print("random state:", random)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test, random_state=random)
    vectorizer = TfidfVectorizer(use_idf=True, smooth_idf=False)
    X_train_vect = vectorizer.fit_transform(X_train)
    X_test_vect = vectorizer.transform(X_test)
    
    # Random Forest
    rf_classifier = RandomForestClassifier(n_estimators=1000, n_jobs=-1, random_state=50, max_leaf_nodes=30)
    rf_classifier.fit(X_train_vect, y_train)
    train_score_rf = rf_classifier.score(X_train_vect, y_train)
    print("Random Forest Training Score:", train_score_rf)
    predict_rf = rf_classifier.predict(X_test_vect)
    accuracy_rf = accuracy_score(y_test, predict_rf)
    confusion_rf = confusion_matrix(y_test, predict_rf)
    print('Random Forest Confusion Matrix:\n', confusion_rf)
    classification_rf = classification_report(y_test, predict_rf)
    print("Random Forest Classification Report:\n", classification_rf)
    print("Random Forest Accuracy Score:", round(accuracy_rf, 2))
    recall_rf = recall_score(y_test, predict_rf, average='weighted')
    print("Random Forest Recall Score:", recall_rf)
    precision_rf = precision_score(y_test, predict_rf, average='weighted')
    print("Random Forest Precision Score:", precision_rf)
    print("\n")
    random_num_rf.append(random)
    matrix_rf.append(confusion_rf)
    report_rf.append(classification_rf)
    acc_num_rf.append(accuracy_rf)
    re_num_rf.append(recall_rf)
    pre_num_rf.append(precision_rf)
    test_num_rf.append(test)
    print("=================================================================")
    
#     # Decision Tree
#     dt_classifier = DecisionTreeClassifier()
#     dt_classifier.fit(X_train_vect, y_train)
#     train_score_dt = dt_classifier.score(X_train_vect, y_train)
#     print("Decision Tree Training Score:", train_score_dt)
#     predict_dt = dt_classifier.predict(X_test_vect)
#     accuracy_dt = accuracy_score(y_test, predict_dt)
#     confusion_dt = confusion_matrix(y_test, predict_dt)
#     print('Decision Tree Confusion Matrix:\n', confusion_dt)
#     classification_dt = classification_report(y_test, predict_dt)
#     print("Decision Tree Classification Report:\n", classification_dt)
#     print("Decision Tree Accuracy Score:", round(accuracy_dt, 2))
#     recall_dt = recall_score(y_test, predict_dt, average='weighted')
#     print("Decision Tree Recall Score:", recall_dt)
#     precision_dt = precision_score(y_test, predict_dt, average='weighted')
#     print("Decision Tree Precision Score:", precision_dt)
#     print("\n")
#     random_num_dt.append(random)
#     matrix_dt.append(confusion_dt)
#     report_dt.append(classification_dt)
#     acc_num_dt.append(accuracy_dt)
#     re_num_dt.append(recall_dt)
#     pre_num_dt.append(precision_dt)
#     test_num_dt.append(test)
#     print("=================================================================")


test size: 0.1
random state: 42
Random Forest Training Score: 0.8320738874895046
Random Forest Confusion Matrix:
 [[57 17]
 [26 33]]
Random Forest Classification Report:
               precision    recall  f1-score   support

     negatif       0.69      0.77      0.73        74
     positif       0.66      0.56      0.61        59

    accuracy                           0.68       133
   macro avg       0.67      0.66      0.67       133
weighted avg       0.67      0.68      0.67       133

Random Forest Accuracy Score: 0.68
Random Forest Recall Score: 0.6766917293233082
Random Forest Precision Score: 0.6748817827701785


test size: 0.2
random state: 42
Random Forest Training Score: 0.8479697828139755
Random Forest Confusion Matrix:
 [[113  38]
 [ 42  72]]
Random Forest Classification Report:
               precision    recall  f1-score   support

     negatif       0.73      0.75      0.74       151
     positif       0.65      0.63      0.64       114

    accuracy                 

In [53]:
data_rf = {'test_size': test_num_rf,
           'random_state': random_num_rf,
           'confusion_matrix': matrix_rf,
           'accuracy': acc_num_rf,
           'recall': re_num_rf,
           'precision': pre_num_rf}

optimal_rf = pd.DataFrame(data_rf)

# Format confusion matrix, accuracy, recall, dan precision
optimal_rf['confusion_matrix'] = optimal_rf['confusion_matrix'].apply(lambda x: str(x))
optimal_rf['accuracy'] = optimal_rf['accuracy'].apply(lambda x: round(x, 6))
optimal_rf['recall'] = optimal_rf['recall'].apply(lambda x: round(x, 6))
optimal_rf['precision'] = optimal_rf['precision'].apply(lambda x: round(x, 6))

optimal_rf

test_size  random_state         confusion_matrix  accuracy    recall  \
0        0.1            42      [[57 17]\n [26 33]]  0.676692  0.676692   
1        0.2            42  [[113  38]\n [ 42  72]]  0.698113  0.698113   
2        0.3            42  [[160  62]\n [ 72 104]]  0.663317  0.663317   
3        0.4            42  [[208  82]\n [ 93 147]]  0.669811  0.669811   

   precision  
0   0.674882  
1   0.696989  
2   0.661730  
3   0.668792

In [54]:
#@GRADIENTBOOSTING

In [55]:
from sklearn.ensemble import GradientBoostingClassifier
import xgboost as xgb

random_num_gb = []
matrix_gb = []
report_gb = []
acc_num_gb = []
re_num_gb = []
pre_num_gb = []
test_num_gb = []

random_num_xgb = []
matrix_xgb = []
report_xgb = []
acc_num_xgb = []
re_num_xgb = []
pre_num_xgb = []
test_num_xgb = []

for test in [0.1, 0.2, 0.3, 0.4]:
    random = 42
    print("test size:", test)
    print("random state:", random)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test, random_state=random)
    vectorizer = TfidfVectorizer(use_idf=True, smooth_idf=False)
    X_train_vect = vectorizer.fit_transform(X_train)
    X_test_vect = vectorizer.transform(X_test)
    
    # Gradient Boosting
    gb_classifier = GradientBoostingClassifier(n_estimators = 400, learning_rate = 0.1, max_depth = 3)
    gb_classifier.fit(X_train_vect, y_train)
    train_score_gb = gb_classifier.score(X_train_vect, y_train)
    print("Gradient Boosting Training Score:", train_score_gb)
    predict_gb = gb_classifier.predict(X_test_vect)
    accuracy_gb = accuracy_score(y_test, predict_gb)
    confusion_gb = confusion_matrix(y_test, predict_gb)
    print('Gradient Boosting Confusion Matrix:\n', confusion_gb)
    classification_gb = classification_report(y_test, predict_gb)
    print("Gradient Boosting Classification Report:\n", classification_gb)
    print("Gradient Boosting Accuracy Score:", round(accuracy_gb, 2))
    recall_gb = recall_score(y_test, predict_gb, average='weighted')
    print("Gradient Boosting Recall Score:", recall_gb)
    precision_gb = precision_score(y_test, predict_gb, average='weighted')
    print("Gradient Boosting Precision Score:", precision_gb)
    print("\n")
    random_num_gb.append(random)
    matrix_gb.append(confusion_gb)
    report_gb.append(classification_gb)
    acc_num_gb.append(accuracy_gb)
    re_num_gb.append(recall_gb)
    pre_num_gb.append(precision_gb)
    test_num_gb.append(test)
    print("=================================================================")
    
#     # Extreme Gradient Boosting (XGBoost)
#     xgb_classifier = xgb.XGBClassifier()
#     xgb_classifier.fit(X_train_vect, y_train)
#     train_score_xgb = xgb_classifier.score(X_train_vect, y_train)
#     print("XGBoost Training Score:", train_score_xgb)
#     predict_xgb = xgb_classifier.predict(X_test_vect)
#     accuracy_xgb = accuracy_score(y_test, predict_xgb)
#     confusion_xgb = confusion_matrix(y_test, predict_xgb)
#     print('XGBoost Confusion Matrix:\n', confusion_xgb)
#     classification_xgb = classification_report(y_test, predict_xgb)
#     print("XGBoost Classification Report:\n", classification_xgb)
#     print("XGBoost Accuracy Score:", round(accuracy_xgb, 2))
#     recall_xgb = recall_score(y_test, predict_xgb, average='weighted')
#     print("XGBoost Recall Score:", recall_xgb)
#     precision_xgb = precision_score(y_test, predict_xgb, average='weighted')
#     print("XGBoost Precision Score:", precision_xgb)
#     print("\n")
#     random_num_xgb.append(random)
#     matrix_xgb.append(confusion_xgb)
#     report_xgb.append(classification_xgb)
#     acc_num_xgb.append(accuracy_xgb)
#     re_num_xgb.append(recall_xgb)
#     pre_num_xgb.append(precision_xgb)
#     test_num_xgb.append(test)
#     print("=================================================================")


test size: 0.1
random state: 42
Gradient Boosting Training Score: 1.0
Gradient Boosting Confusion Matrix:
 [[53 21]
 [19 40]]
Gradient Boosting Classification Report:
               precision    recall  f1-score   support

     negatif       0.74      0.72      0.73        74
     positif       0.66      0.68      0.67        59

    accuracy                           0.70       133
   macro avg       0.70      0.70      0.70       133
weighted avg       0.70      0.70      0.70       133

Gradient Boosting Accuracy Score: 0.7
Gradient Boosting Recall Score: 0.6992481203007519
Gradient Boosting Precision Score: 0.7004567429502718


test size: 0.2
random state: 42
Gradient Boosting Training Score: 1.0
Gradient Boosting Confusion Matrix:
 [[108  43]
 [ 30  84]]
Gradient Boosting Classification Report:
               precision    recall  f1-score   support

     negatif       0.78      0.72      0.75       151
     positif       0.66      0.74      0.70       114

    accuracy            

In [56]:
import pandas as pd

data_gb = {'test_size': test_num_gb,
           'random_state': random_num_gb,
           'confusion_matrix': matrix_gb,
           'accuracy': acc_num_gb,
           'recall': re_num_gb,
           'precision': pre_num_gb}

optimal_gb = pd.DataFrame(data_gb)

# Format confusion matrix, accuracy, recall, dan precision
optimal_gb['confusion_matrix'] = optimal_gb['confusion_matrix'].apply(lambda x: str(x))
optimal_gb['accuracy'] = optimal_gb['accuracy'].apply(lambda x: round(x, 6))
optimal_gb['recall'] = optimal_gb['recall'].apply(lambda x: round(x, 6))
optimal_gb['precision'] = optimal_gb['precision'].apply(lambda x: round(x, 6))

optimal_gb


test_size  random_state         confusion_matrix  accuracy    recall  \
0        0.1            42      [[53 21]\n [19 40]]  0.699248  0.699248   
1        0.2            42  [[108  43]\n [ 30  84]]  0.724528  0.724528   
2        0.3            42  [[160  62]\n [ 58 118]]  0.698492  0.698492   
3        0.4            42  [[209  81]\n [ 93 147]]  0.671698  0.671698   

   precision  
0   0.700457  
1   0.730474  
2   0.699280  
3   0.670627